#!/bin/bash
export MAPROULETTE_SETTINGS=/srv/www/{{instance}}/config.py
source /srv/www/{{instance}}/virtualenv/bin/activate
export FLASK_APP=maproulette
flask cleanstaletasks >> /tmp/clean_stale_tasks.log
